export { Layout as PageLayout } from "./Layout"
export { Home as PageHome } from "./Home"
export { Comentario as PageComentario } from "./Comentario"
export { Cadastrar as PageCadastrar } from "./Cadastrar"
export { Login as PageLogin } from "./Login"

export { Adm as PageAdm } from "./Adm"
export { Duna as PageDuna } from "./Duna"
export { Zodiac as PageZodiac } from "./Zodiac"
export { Batman as PageBatman } from "./Batman"